%% Helper function to apply a Wiener filter generated by miso_firwiener
% r = applyWiener(W, data)
% Generates r[econstructed data] from Wiener filter W applied to data
% Data accepted as columns
function r = applyWiener(W, data)
    r = zeros([size(data,1) 1]);
    for i=1:size(W,2)
        r = r + filter(W(:,i),1,data(:,i));
    end
end
